-- ============================================================
-- SETUP E-COMMERCE (PAKASIR INTEGRATION)
-- ============================================================

-- ─── DIGITAL PRODUCTS ───
CREATE TABLE IF NOT EXISTS digital_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL, -- e.g., 'AKUN', 'LAYANAN'
  title TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  icon TEXT, -- nama icon dari lucide-react, misal: 'Mail', 'Shield'
  status TEXT DEFAULT 'TERSEDIA',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Digital Products (Publik bisa membaca)
ALTER TABLE digital_products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read digital_products" ON digital_products;
CREATE POLICY "Public read digital_products" ON digital_products FOR SELECT USING (true);

-- Masukkan data awal (contoh sesuai screenshot sebelumnya)
INSERT INTO digital_products (category, title, description, price, icon)
VALUES 
  ('AKUN', 'GMAIL ( MANUAL CREATE )', 'CREATE MANUAL ID & PASS RANDOM\nGARANSI UP TO 1 HOURS!', 15000, 'Mail'),
  ('AKUN', 'DISCORD ( OLD 2016+ )', 'FULL ACCESS, REAL MEMBER ACTIVITY\nANTI-HACKBACK GUARANTEE!', 45000, 'Shield'),
  ('LAYANAN', 'JASA JOKI GT', 'PROSES CEPAT & AMAN 100%\nBISA REQUEST TARGET BGL/DL', 25000, 'Zap')
ON CONFLICT DO NOTHING;

-- ─── PRODUCT STOCK ───
CREATE TABLE IF NOT EXISTS product_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES digital_products(id) ON DELETE CASCADE,
  credentials_data TEXT NOT NULL, -- Format bebas: "Email: xxx | Pass: yyy"
  is_sold BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Product Stock (SANGAT RAHASIA, tidak boleh dibaca publik)
ALTER TABLE product_stock ENABLE ROW LEVEL SECURITY;
-- Hanya service_role (Admin API) yang bisa baca/tulis. Publik tidak punya akses sama sekali.

-- ─── ORDERS ───
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no TEXT UNIQUE NOT NULL, -- e.g., INV-20240911-XXXX
  product_id BIGINT REFERENCES digital_products(id),
  customer_wa TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  payment_method TEXT,
  qris_string TEXT,
  payment_status TEXT DEFAULT 'pending', -- pending, paid, failed, expired
  stock_id BIGINT REFERENCES product_stock(id), -- Nullable, akan diisi jika stok dibooking
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- RLS Orders (Publik hanya bisa baca miliknya sendiri berdasarkan invoice_no, tapi kita disable policy public read untuk amannya. 
-- Semua query order akan dilewatkan API route Next.js menggunakan service_role).
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
-- Tidak ada public policy. Semua akses di-handle backend API.
