-- Hapus tabel jika sudah ada (hati-hati jika ada data penting)
-- DROP TABLE IF EXISTS accounts;
-- DROP TABLE IF EXISTS testimonials;
-- DROP TABLE IF EXISTS reputations;

-- Tabel untuk Akun Growtopia
CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  image_url TEXT,
  status TEXT DEFAULT 'available', -- 'available' atau 'sold'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabel untuk Testimoni
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_name TEXT NOT NULL,
  item_bought TEXT NOT NULL,
  rating INTEGER DEFAULT 5,
  content TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabel untuk Live Reputation (+Rep)
CREATE TABLE IF NOT EXISTS reputations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_name TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Mengaktifkan Realtime untuk tabel reputations agar feed bisa update secara langsung
ALTER PUBLICATION supabase_realtime ADD TABLE reputations;

-- (Opsional) Mengaktifkan Realtime untuk tabel lain jika perlu
ALTER PUBLICATION supabase_realtime ADD TABLE accounts;
ALTER PUBLICATION supabase_realtime ADD TABLE testimonials;

-- ============================================================
-- KEBIJAKAN RLS (Row Level Security) - WAJIB UNTUK KEAMANAN
-- ============================================================

-- ─── ACCOUNTS ───
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read accounts" ON accounts;
CREATE POLICY "Public read accounts" ON accounts FOR SELECT USING (true);

-- ─── TESTIMONIALS ───
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read testimonials" ON testimonials;
CREATE POLICY "Public read testimonials" ON testimonials FOR SELECT USING (true);

-- ─── REPUTATIONS ───
ALTER TABLE reputations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read approved reputations" ON reputations;
CREATE POLICY "Public read approved reputations" ON reputations FOR SELECT USING (status = 'approved');
DROP POLICY IF EXISTS "Public insert pending reputations" ON reputations;
CREATE POLICY "Public insert pending reputations" ON reputations FOR INSERT WITH CHECK (status = 'pending');

-- ─── PAGE VIEWS ───
CREATE TABLE IF NOT EXISTS page_views (
  id INT PRIMARY KEY DEFAULT 1,
  view_count BIGINT DEFAULT 0
);
INSERT INTO page_views (id, view_count) VALUES (1, 0) ON CONFLICT (id) DO NOTHING;
ALTER TABLE page_views ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read page_views" ON page_views;
CREATE POLICY "Public read page_views" ON page_views FOR SELECT USING (true);

-- Fungsi untuk menambah view +1 secara atomik (SECURITY DEFINER agar bisa bypass RLS)
CREATE OR REPLACE FUNCTION increment_page_view()
RETURNS void AS $$
BEGIN
  UPDATE page_views SET view_count = view_count + 1 WHERE id = 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ─── SITE SETTINGS ───
CREATE TABLE IF NOT EXISTS site_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  description TEXT
);
INSERT INTO site_settings (key, value, description)
VALUES 
  ('wa_kucaidl', '6283163349669', 'Nomor WhatsApp Utama (KUCAIDL)'),
  ('wa_kucaiakun', '6283892385335', 'Nomor WhatsApp Akun (KucaiAkun)')
ON CONFLICT (key) DO NOTHING;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read site_settings" ON site_settings;
CREATE POLICY "Public read site_settings" ON site_settings FOR SELECT USING (true);

-- ─── STORAGE ───
INSERT INTO storage.buckets (id, name, public) 
VALUES ('kucaidl', 'kucaidl', true) 
ON CONFLICT DO NOTHING;

-- Public read access for images
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'kucaidl');

-- Remove dangerous open upload/delete policies
DROP POLICY IF EXISTS "Allow all uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow all deletes" ON storage.objects;
-- Admin uploads go through server API with service_role key (bypasses RLS)

-- ─── PRODUCTS (jika tabel sudah ada) ───
ALTER TABLE IF EXISTS products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read products" ON products;
CREATE POLICY "Public read products" ON products FOR SELECT USING (true);

-- ─── SETTINGS (jika tabel sudah ada) ───
ALTER TABLE IF EXISTS settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read settings" ON settings;
CREATE POLICY "Public read settings" ON settings FOR SELECT USING (true);
